# .rubocop.yml

inherit_from:
  - rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 10

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'spec/**/*'

RSpec:
  AllCops:
    TargetRubyVersion: 3.2
